### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by LysanderT** [LysanderT/code-arena#1]
- [ ] Add db to store the data collected.
- [ ] Add 'Request more languages' feature in the language choice box.
- [ ] Add feedback feature for each answer card. Let user choose from limited feedback options.
